apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytest
  template:
    metadata:
      labels:
        app: mytest
    spec:
      containers:
      - name: test
        image: webappapi.azurecr.io/newapimulti:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
