apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalers.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  version: v1
  names:
    kind: VerticalPodAutoscaler
    plural: verticalpodautoscalers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            targetRef:
              type: object
              required:
              - apiVersion
              - kind
              - name
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
            updatePolicy:
              type: object
              properties:
                updateMode:
                  type: string
                  enum:
                  - "Off"
                  - "Auto"
          required:
          - targetRef
  subresources:
    status: {}
